name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

jobs:
  build:
    uses: ./.github/workflows/continuous-integration.yml

  nuget-push:
    runs-on:  windows-2022
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: package-windows-2022
          path: ./package

      - name: Publish to nuget
        run: dotnet nuget push ".\package\*.nupkg" --no-symbols --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_KEY }}
